- Cargo.lock
- Cargo.toml
- README.md
- crates/extensions/Cargo.toml
- crates/integration/Cargo.toml
- crates/integration/contracts/Computation.sol
- crates/integration/contracts/flipper.sol
- crates/integration/src/mock_runtime.rs
- crates/llvm-context/src/eravm/const.rs
- crates/llvm-context/src/eravm/context/address_space.rs
- crates/llvm-context/src/eravm/context/function/runtime/entry.rs
- crates/llvm-context/src/eravm/context/mod.rs
- crates/llvm-context/src/eravm/evm/calldata.rs
- crates/llvm-context/src/eravm/evm/crypto.rs
- crates/pallet-contracts-pvm-llapi/Cargo.toml
- crates/pallet-contracts-pvm-llapi/src/polkavm_guest.c
- crates/pallet-contracts-pvm-llapi/src/polkavm_guest.h
- crates/stdlib/Cargo.toml
Use PolkaVM heap instead of .bss arena.
> Polkavm heap

- crates/common/src/byte_length.rs
- crates/llvm-context/src/polkavm/context/mod.rs
Stack allocations should happen as early as possible
> always build alloca in the entry block

- crates/solidity/src/lib.rs
- crates/solidity/src/process/input.rs
- crates/solidity/src/process/mod.rs
- crates/solidity/src/project/mod.rs
- crates/solidity/src/test_utils.rs
> Rremove the test encoding option

- crates/integration/contracts/Value.sol
- crates/integration/src/tests.rs
- crates/llvm-context/src/polkavm/const/runtime_api.rs
- crates/llvm-context/src/polkavm/context/mod.rs
- crates/llvm-context/src/polkavm/evm/call.rs
- crates/llvm-context/src/polkavm/evm/ether_gas.rs
- crates/runtime-api/src/polkavm_imports.c
**Pull Request Summary**
- Fix `balance_of` implementation to use correct runtime api
- Add `build_address_argument_store` helper to be used for address arguments
> Fix implementation for balance_of

- .github/workflows/rust.yml
- crates/solidity/src/solc/mod.rs
[No surfacing changes.](https://soliditylang.org/blog/2024/10/09/solidity-0.8.28-release-announcement/)
> support solc 0.8.28

- crates/integration/codesize.json
- crates/llvm-context/src/target_machine/mod.rs
> update LLVM target features

- crates/integration/contracts/Transaction.sol
- crates/integration/src/tests.rs
- crates/llvm-context/src/polkavm/evm/context.rs
- crates/runtime-api/src/polkavm_imports.c
- crates/runtime-api/src/polkavm_imports.rs
> support the origin opcode

- Cargo.lock
- Cargo.toml
- crates/runner/src/lib.rs
Sync with polkadot-sdk and polkavm
> update the polkadot-sdk and polkavm dependencies

- Cargo.lock
- Cargo.toml
- crates/integration/contracts/ERC20.sol
- crates/integration/src/tests.rs
- crates/llvm-context/src/polkavm/evm/ext_code.rs
- crates/runtime-api/src/polkavm_imports.c
- Bump the polkadot sdk
- Implement the code size opcodes
- Fix the ERC20.sol integration test
> implement the code size opcodes

- crates/solidity/src/project/contract/metadata.rs
- crates/solidity/src/project/contract/mod.rs
> use the long revive version string in the contract metadata

- Cargo.lock
- Cargo.toml
- crates/integration/codesize.json
- crates/integration/contracts/GasLeft.sol
- crates/integration/src/tests.rs
- crates/llvm-context/src/polkavm/evm/ether_gas.rs
- crates/runtime-api/src/polkavm_imports.c
- crates/runtime-api/src/polkavm_imports.rs
Update the pallet version supporting the `ref_time_left` syscall method and use it's return value as the `GAS` left.
> implement the gas opcode

- Cargo.lock
- Cargo.toml
- crates/integration/contracts/GasLimit.sol
- crates/integration/src/tests.rs
- crates/llvm-context/src/polkavm/evm/context.rs
- crates/runner/src/runtime.rs
- crates/runtime-api/src/polkavm_imports.c
- crates/runtime-api/src/polkavm_imports.rs
Update the polkadot-sdk to the latest version implementing the gas limit syscall and translate the instruction accordingly.
> implement the gas limit opcode

- Cargo.lock
- Cargo.toml
- crates/llvm-context/src/polkavm/evm/context.rs
- crates/runtime-api/src/polkavm_imports.c
- crates/runtime-api/src/polkavm_imports.rs
Update to the latest polkadot-sdk version implementing the gas price syscall.
> implement the gas price opcode

- LLVM.lock
Pin the LLVM version to ensure reproducible builds.
> pin the LLVM version

- CHANGELOG.md
- crates/solidity/src/resolc/main.rs
- crates/solidity/src/solc/mod.rs
- crates/solidity/src/solc/solc_compiler.rs
- crates/solidity/src/solc/soljson_compiler.rs
- crates/solidity/src/solc/standard_json/output/error/mod.rs
- crates/solidity/src/solc/version.rs
- crates/solidity/src/tests/messages.rs
- Fix the custom warning messages.
- Unify the solc version validation for all targets.
> solidity: update custom warnings and version validation

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- crates/differential/genesis.json
- crates/differential/src/lib.rs
- Pin the geth version to a working one.
- Update the runner for the latest geth version.
> CI: fix and pin geth

- crates/integration/contracts/FunctionType.sol
- crates/integration/src/tests.rs
> integration: add function return type test

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/integration/contracts/DelegateCaller.sol
- crates/integration/src/tests.rs
> integration: add delegate call corner case test

- .github/workflows/release.yml
PR modifies release workflow according to changes requested in https://github.com/paritytech/revive/issues/162#issuecomment-2751287953
cc https://github.com/paritytech/revive/issues/162
cc https://github.com/paritytech/devops/issues/3890
> ci: modify release according to #162

- CHANGELOG.md
- crates/integration/contracts/AddressPredictor.sol
- crates/integration/src/cases.rs
- crates/integration/src/tests.rs
- crates/llvm-context/src/polkavm/evm/create.rs
Found in https://github.com/paritytech/contract-issues/issues/45, thanks @albertov19 and @sekisamu
> bugfix missing byte swap for the create2 salt value

- .github/scripts/json_generator.py
- .github/workflows/release.yml
PR addresses https://github.com/paritytech/revive/issues/162#issuecomment-2783173447
> Remove path from release json and add sha256

- .github/workflows/release.yml
- .gitignore
- package-lock.json
> Fix  npm-release job

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- js/resolc/package.json
- js/resolc/src/index.ts
add missing patch and rename release
> Replace release 0.1.0-dev.15 with 0.1.0-dev.16

- js/resolc/package.json
- js/resolc/src/index.test.ts
- js/resolc/src/index.ts
- package-lock.json
second take on #339 
turns out that the resolve-pkg npm package was also failing to properly resolve package with an exports field define in the package.json.
This fixes it and add a test case with such a package
> @parity/resolc fix sol file resolutions

- .github/scripts/json_generator_nightly.py
cc https://github.com/paritytech/revive/pull/357
> Make nigthly version semver compliant

- CHANGELOG.md
- crates/integration/codesize.json
- crates/llvm-context/src/polkavm/context/function/runtime/deploy_code.rs
- crates/llvm-context/src/polkavm/context/function/runtime/entry.rs
- crates/llvm-context/src/polkavm/context/function/runtime/runtime_code.rs
- crates/llvm-context/src/polkavm/context/mod.rs
- crates/llvm-context/src/polkavm/context/runtime.rs
- crates/llvm-context/src/polkavm/context/tests.rs
- crates/yul/src/parser/statement/assignment.rs
- crates/yul/src/parser/statement/block.rs
- crates/yul/src/parser/statement/expression/function_call/mod.rs
- crates/yul/src/parser/statement/for_loop.rs
- crates/yul/src/parser/statement/function_definition.rs
- crates/yul/src/parser/statement/if_conditional.rs
- crates/yul/src/parser/statement/object.rs
- crates/yul/src/parser/statement/switch/mod.rs
- crates/yul/src/parser/statement/variable_declaration.rs
- Add column numbers to debug information.
- Do not build allocas at entry for now.
> add columns to debug information
