paritytech/revive

.gitignore, package.json
- Introduced `npm` workspaces to manage CLI tests from the root directory.
- Enabled simplified npm dependency installation from the root directory. 
- Updated `.gitignore` to align with the new workspace structure.
From the root directory
To install repo npm packages, run:
```bash
npm install && npm fund
```
To run related tests, run:
```bash
npm run test:cli
```
=> feat: added npm workspaces support

Makefile, README.md
This PR introduces a way for the `zksolc` binary to automatically be updated/copied to `.cargo/bin` after each build to resolves the issue of having to manually update the $PATH or each time keep running `cargo install --path crates/solidity`, which was a recurring annoyance during testing and development.
To install the project dependencies, run:
```bash
make install
```
To clean the project directory from all build artifacts and dependencies, run:
```bash
make clean
```
To run integration tests, use
```bash
make test-integration
```
To run the project's tests, ( both Rust and npm tests ) use:
```bash
make test
```
To run only solidity crate test, use:
```bash
make test-solidity
```
To run only the CLI tests, use:
```bash
make test-cli
```
=> feat: streamline bin updates during developement

Makefile
Since 'make test' is frequently used during development, adding the codebase formatting target as a prerequisite to it, will help maintain consistency in the codebase more easily.
During testing, formatting will automatically be applied 
```bash
make test
```
If you only want to format the codebase without running the tests, you should just run:
```bash
make format
```
=> chore: added code formating target

Cargo.lock, Cargo.toml, crates/benchmarks/benches/execute.rs, crates/integration/codesize.json, crates/solidity/Cargo.toml, crates/solidity/src/build/contract.rs, crates/solidity/src/evmla/ethereal_ir/entry_link.rs, crates/solidity/src/evmla/ethereal_ir/function/block/element/mod.rs, crates/solidity/src/evmla/ethereal_ir/function/block/mod.rs, crates/solidity/src/evmla/ethereal_ir/function/mod.rs, crates/solidity/src/evmla/ethereal_ir/mod.rs, crates/solidity/src/project/contract/ir/evmla.rs, crates/solidity/src/project/contract/ir/mod.rs, crates/solidity/src/project/contract/ir/yul.rs, crates/solidity/src/project/contract/mod.rs, crates/solidity/src/tests/cli-tests/tests/asm.test.ts, crates/solidity/src/tests/cli-tests/tsconfig.json, crates/solidity/src/yul/parser/statement/block.rs, crates/solidity/src/yul/parser/statement/code.rs, crates/solidity/src/yul/parser/statement/expression/function_call/mod.rs, crates/solidity/src/yul/parser/statement/expression/mod.rs, crates/solidity/src/yul/parser/statement/for_loop.rs, crates/solidity/src/yul/parser/statement/function_definition.rs, crates/solidity/src/yul/parser/statement/if_conditional.rs, crates/solidity/src/yul/parser/statement/object.rs, crates/solidity/src/yul/parser/statement/switch/mod.rs, crates/solidity/src/zksolc/arguments.rs, crates/solidity/src/zksolc/main.rs
- Integratd the disassembler
- updated `asm.test` to check for the correct patterns in the assembly text.
- addressed tsconfig conflict
```bash
zksolc contract.sol --asm --output-dir './tmpdir'
```
The assembly `.zasm` file will be outputed in the `tmpdir` directory
---
```bash
make test-cli
```
Now `asm.test` working properly
=> feat: use PolkaVM disassembler

.gitignore, build-llvm.sh
Adjust the llvm build script to put the llvm and compiler-rt build directories outside the llvm-project source directory. A new build directory 'build' at the toplevel of the revive directory is used instead. LLVM is built into 'build/llvm' and compiler-rt into 'build/compiler-rt'.
Adjust .gitignore to ignore the contents of the build directory.
This is intended to keep the build artifacts separate from the upstream sources and any changes made as part of the revive work.
=> Put llvm and compiler-rt build directories in one place.

crates/llvm-context/src/debug_config/ir_type.rs, crates/llvm-context/src/debug_config/mod.rs, crates/solidity/src/process/mod.rs, crates/solidity/src/resolc/arguments.rs, crates/solidity/src/resolc/main.rs
Add option --recursive-process-input <filename> for use with --recursive-process to specify the name of a file to use instead of reading from stdin.
If --debug-output-dir is set, dump the file passed to the recursive invocation of the compiler as a JSON file suitable for use with --recursive-process-input.
These changes are intended to support debugging the compiler and are only available with DEBUG builds.
=> [solidity,llvm-context] Improve support for debugging the compiler

Cargo.lock, Cargo.toml, crates/benchmarks/src/lib.rs, crates/integration/codesize.json, crates/integration/src/tests.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/runner/src/lib.rs, crates/runner/src/runtime.rs, crates/runner/src/specs.rs
- Update to `pallet_revive` using 20byte addresses
- Change the key length pointer in the storage APIs to the sentinel value
=> `pallet_revive`: Account20

crates/solidity/src/resolc/arguments.rs
Fix the check for the validity of `--recursive-process-input` to make sure that it is only selected when `--recursive-process` is also selected.
=> [solidity] Fix wrong check on recursive-process-input CLI option.

.github/workflows/build-revive-debian.yml, Cargo.toml, Makefile, utils/build-debian-builder.sh, utils/build-revive.sh, utils/revive-builder-debian.dockerfile, utils/run-debian-builder.sh
Makefile: Add target 'install-revive' to build revive with the installation path specified by variable REVIVE_INSTALL_DIR.
Add utils directory with scripts for building revive in a container.
Add utils/build-revive.sh taking option argument '-o <install-dir>' to build revive with the specified install directory.
Add utils/revive-builder-debian.dockerfile to make a docker container for building revive in a Debian environment.
=> [workflows] Add workflow for building revive in a debian container.

Makefile
`--allow dead_code` will resolve after #66
=> deny clippy warnings by default

Cargo.lock, Cargo.toml, crates/integration/codesize.json, crates/integration/contracts/Immutables.sol, crates/integration/src/tests.rs, crates/llvm-context/src/lib.rs, crates/llvm-context/src/polkavm/const/runtime_api.rs, crates/llvm-context/src/polkavm/context/function/mod.rs, crates/llvm-context/src/polkavm/context/function/runtime/entry.rs, crates/llvm-context/src/polkavm/context/function/runtime/immutable_data_load.rs, crates/llvm-context/src/polkavm/context/function/runtime/mod.rs, crates/llvm-context/src/polkavm/context/global.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/llvm-context/src/polkavm/context/solidity_data.rs, crates/llvm-context/src/polkavm/evm/immutable.rs, crates/llvm-context/src/polkavm/evm/return.rs, crates/runtime-api/Cargo.toml, crates/runtime-api/src/immutable_data.rs, crates/runtime-api/src/lib.rs, crates/runtime-api/src/polkavm_imports.c, crates/solidity/src/evmla/assembly/mod.rs, crates/solidity/src/evmla/ethereal_ir/function/block/element/mod.rs, crates/solidity/src/yul/parser/statement/expression/function_call/mod.rs, crates/solidity/src/yul/parser/statement/object.rs
This PR implements immutable variables in the codegen backend.
Notes on the implementation (this also differences from the ZKSync implementation):
- Do not explicitly store the index. The stored index is used to calculate the index itself. It follows that it can always be implied.
- We only store the final immutable data size (and the required memory buffer length) after we finished translating to LLVM IR. This way the observed immutable data size is not depended of the position of translated returns and immutable accesses.
- Do not return immutable data from the constructor; instead use the syscall.
- Lazily load the whole immutable data upon the first access. Once the data is loaded, just read from memory. This works by only syscalling into `get_immutable_data` if the immutable data …
=> implement immutable variables codegen

crates/llvm-context/src/optimizer/settings/mod.rs, crates/llvm-context/src/polkavm/context/function/llvm_runtime.rs, crates/llvm-context/src/polkavm/context/function/mod.rs, crates/llvm-context/src/polkavm/context/function/runtime/deploy_code.rs, crates/llvm-context/src/polkavm/context/function/runtime/entry.rs, crates/llvm-context/src/polkavm/context/function/runtime/runtime_code.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/llvm-context/src/polkavm/context/yul_data.rs, crates/llvm-context/src/polkavm/mod.rs, crates/solidity/src/evmla/ethereal_ir/function/mod.rs, crates/solidity/src/lib.rs, crates/solidity/src/process/input.rs, crates/solidity/src/process/mod.rs, crates/solidity/src/project/contract/mod.rs, crates/solidity/src/project/mod.rs, crates/solidity/src/resolc/arguments.rs, crates/solidity/src/resolc/main.rs, crates/solidity/src/solc/standard_json/input/settings/optimizer/mod.rs, crates/solidity/src/test_utils.rs, crates/solidity/src/yul/parser/statement/expression/function_call/mod.rs, crates/solidity/src/yul/parser/statement/function_definition.rs
We can implement them when (and only if) we need.
=> remove some unused features

crates/llvm-context/src/polkavm/context/mod.rs
Some change to runtime api call method to make it easy to read `ll` generated code.
before
```ll
%"runtime API call call" = call i32 @call(i32 %call_argument_pointer)
%is_success.not = icmp eq i32 %"runtime API call call", 0
```
after
```ll
%runtime_api_call_return_value = call i32 @call(i32 %call_argument_pointer)
%is_success = icmp eq i32 %runtime_api_call_return_value, 0
```
=> improve runtime api return value names

crates/differential/src/lib.rs, crates/integration/contracts/Call.sol, crates/runner/src/lib.rs
The pallet returns the `Ok` variant when the transaction did revert, so we should also consider the revert flag.
=> revive-runner: consider only non-reverted transactions as success

Makefile
Also moved the clippy target around next to other test related targets
=> Makefile: remove duplicate workspace tests from the test target

Cargo.lock, Cargo.toml, crates/runner/src/lib.rs, crates/runner/src/runtime.rs, crates/runner/src/specs.rs
- Switch to an unreleased inkwell version which fixes a musl cross compilation bug
- Update the polkadot-sdk dependency
=> update polkadot-sdk and inkwell dependencies

crates/solidity/src/build/mod.rs, crates/solidity/src/lib.rs, crates/solidity/src/missing_libraries.rs, crates/solidity/src/project/contract/metadata.rs, crates/solidity/src/resolc/main.rs, crates/solidity/src/solc/combined_json/mod.rs, crates/solidity/src/solc/standard_json/output/mod.rs, crates/solidity/src/test_utils.rs, crates/solidity/src/version.rs
This PR renames the revive metadata fields and includes the commit hash in the revive version (similar to what solc does).
=> solidity: rename the revive metadata

Cargo.lock, Cargo.toml, crates/solidity/Cargo.toml, crates/solidity/build.rs
From the `git2` crate:
> The source for libgit2 is included in the libgit2-sys crate so there's no need to pre-install the libgit2 library
So it should work even if git is not installed on the build host
=> fix the commit sha in the version string

.github/workflows/build-revive-debian.yml, .github/workflows/build-revive-wasm.yml, .github/workflows/rust.yml
Stick the CI runner host version: https://github.com/actions/runner-images/issues/10636
The LLVM build is expecting older dependencies. Will resolve once we have our own LLVM builds.
=> fix the CI runner version

Cargo.lock, Cargo.toml, crates/integration/contracts/BaseFee.sol, crates/integration/src/tests.rs, crates/llvm-context/src/polkavm/evm/context.rs, crates/runtime-api/src/polkavm_imports.c, crates/runtime-api/src/polkavm_imports.rs
We implemented a corresponding syscall in the pallet so that existing contracts will not break if we ever need to change it.
=> implement the basefee opcode

.github/workflows/build-revive-wasm.yml, Makefile, js/examples/node/revive.js, js/examples/node/run_revive.js, js/package.json, js/tests/node.test.mjs, package.json
Add tests for the Revive WASM version, running them on macOS, Windows, and Linux using both Bun and Node.js.
=> Add tests for the Revive WASM version

Makefile
Documentation of the contracts stack was moved into a dedicated repository.
=> Remove the docs Makefile targets

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, Makefile, crates/integration/Cargo.toml, crates/linker/Cargo.toml, crates/llvm-builder/Cargo.toml, crates/llvm-context/Cargo.toml, crates/runner/Cargo.toml, crates/solidity/Cargo.toml
- Update the used workspace dependencies.
- Remove the unused workspace dependencies.
- Add the machete CI workflow.
=> vet workspace dependencies

.cargo/config.toml, Makefile
- Move the emscripten target flags into the target configuration.
- Improve the readability of the Makefile.
=> vet the Makefile

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/llvm-context/src/polkavm/context/mod.rs, crates/llvm-context/src/polkavm/evm/call.rs, crates/llvm-context/src/polkavm/evm/create.rs, crates/runner/src/lib.rs, crates/runner/src/runtime.rs, crates/runtime-api/src/calling_convention.rs, crates/runtime-api/src/polkavm_imports.c
Companion to https://github.com/paritytech/polkadot-sdk/pull/7319
=> runtime-api: pass call arguments in registers instead of spilling to stack

CHANGELOG.md, crates/solidity/src/test_utils.rs
Prevents confusions if two tests use different contracts with the same name.
=> integration: bugfix blob cache

CHANGELOG.md, crates/integration/contracts/Balance.sol, crates/integration/contracts/Send.sol, crates/integration/src/cases.rs, crates/integration/src/tests.rs, crates/llvm-context/src/polkavm/evm/call.rs, crates/solidity/src/solc/standard_json/output/error/mod.rs
Closes #117
Improves related tests as a drive-by.
=> llvm-context: disable call re-entrancy for send and transfer

CHANGELOG.md, crates/integration/contracts/MLoad.sol, crates/integration/src/tests.rs, crates/llvm-context/src/polkavm/const/mod.rs, crates/llvm-context/src/polkavm/context/function/runtime/entry.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/runtime-api/src/lib.rs, crates/runtime-api/src/polkavm_imports.c, crates/runtime-api/src/polkavm_imports.rs
Since we are emulating the EVM linear memory heap anyways we can access it directly. Fixes a bug in the old logic as a side effect. Drive-by fixes a missing integer truncate.
Closes #195
Closes #203
=> llvm-context: remove the linear memory pointer indirection

.github/workflows/rust.yml
The new release fixes a bug in the `evm` runner utility so we should be good again.
=> ci: use upstream evm for tests

.github/workflows/release-llvm.yml, RELEASE.md
I've been testing these on a fork with public runners.  
Windows, unfortunately, still needs work, and linux fails on a 6h timeout, when executed on ubuntu-latest 😅.  
But as at least some of it works, let's kick off the review, and hopefully, I'll be able to finish testing workflows and windows LLVM release in parallel (given the duration of the feedback loop on these tasks)
=> LLVM release workflows

.github/workflows/release-llvm.yml, RELEASE.md
Workflow example: https://github.com/paritytech/revive-workflow-test/actions/runs/13440400860
Release example: https://github.com/paritytech/revive-workflow-test/releases/tag/18.1.8-revive.395212b
=> Using workflow_dispatch for LLVM releases

.github/workflows/get-release-artifact.js, .github/workflows/release.yml
This PR depends on #207, so we'll need to merge that one first
Here's how the workflow and release look in fork:
https://github.com/paritytech/revive-workflow-test/actions/runs/13442528853
https://github.com/paritytech/revive-workflow-test/releases/tag/untagged-c2d093272cba97f2eb1c
List of changes: 
* Instead of compiling LLVM, it downloads it from releases, using `.github/workflows/get-release-artifact.js` in `get-llvm-artifact` step, with `curl` / `tar` following
* Added MacOS build with generating unified binary at the end
* Moved release notes generation to the first step to avoid `checkout` at the end
* Joined `create-release` and `upload-assets` jobs into a single `create-release` job
* Replaced archived `actions/upload-release-asset` action and custom release creation with a single …
=> Using released LLVM in revive build & MacOS revive pipeline & pipeline improvements

crates/llvm-builder/tests/build.rs
The tests are supposed to keep trouble on release CI jobs - which run mostly on linux. So there is no need to do all these expensive tests on all plattforms.
The emscripten build is supposed to work well on MacOS because that's what most devs use - but not the CI so if it's broken we can just figure and fix it when issues arise.
=> llvm-builder: only run expensive tests on linux

crates/integration/codesize.json, crates/solidity/src/solc/standard_json/input/settings/selection/file/flag.rs, crates/solidity/src/solc/standard_json/input/settings/selection/file/mod.rs, crates/solidity/src/solc/standard_json/input/settings/selection/mod.rs, crates/solidity/src/solc/standard_json/output/contract/mod.rs
This PR adds per file support for output selection in `--standard-json` inputs this is needed for foundry support. 
This PR also adds `Ir` and `Unknown` flags to the output selection options, ir for the unoptimized IR and `Unknown` to catch unsupported options as they would not be applied anyways.(Although on take 2 it seems like it's better to error out explicitely rather than drop unsupported flags.)
=> Add per file output selection for `--standard-json` mode and some other small foundry support bits.

.github/actions/get-solc/action.yml, .github/workflows/release.yml, crates/lld-sys/build.rs
With LLVM working only minor changes were necessary to get resolc running on Windows.
Release in my branch here: https://github.com/paritytech/revive-alex-workflowtest/releases/tag/v0.1.0-dev.12
=> Release Windows Version

.github/actions/get-solc/action.yml, .github/workflows/release.yml, CHANGELOG.md, crates/integration/codesize.json, crates/integration/contracts/LayoutAt.sol, crates/integration/src/tests.rs, crates/solidity/src/solc/mod.rs, js/build.js, js/package.json
No observable changes w.r.t. YUL compilation.
- Mark solc v0.8.29 as the latest supported version
- Add integration test for solc v0.8.29 specific feature
- Use the latest version on CI
- Drive-by fix linter complaints and a two types in the CI yaml files
=> Support solc v0.8.29

CHANGELOG.md, crates/solidity/src/lib.rs, crates/solidity/src/resolc/arguments.rs, crates/solidity/src/resolc/main.rs
Adds `--supported-solc-versions` cli command to return a semver range of supported `solc` versions. 
Is a hack until #162 is implemented.
=> Add --supported-solc-versions CLI command

CHANGELOG.md, Cargo.lock, crates/llvm-context/Cargo.toml, crates/llvm-context/src/lib.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/llvm-context/src/polkavm/context/tests.rs, crates/llvm-context/src/polkavm/mod.rs, crates/solidity/src/lib.rs, crates/solidity/src/process/input.rs, crates/solidity/src/process/mod.rs, crates/solidity/src/project/contract/metadata.rs, crates/solidity/src/project/contract/mod.rs, crates/solidity/src/project/mod.rs, crates/solidity/src/resolc/arguments.rs, crates/solidity/src/resolc/main.rs, crates/solidity/src/test_utils.rs
- Support for passing LLVM command line options via the prcoess input or providing one or more `--llvm-arg='..'` resolc CLI flag. This allows more fine-grained control over the LLVM backend configuration.
- Make LLVM initialization idempotent.
=> Suport passing arbitrary llvm arguments 

CHANGELOG.md, Cargo.lock, Makefile, crates/runner/Cargo.toml, crates/runner/README.md, crates/runner/src/main.rs, crates/runner/src/specs.rs
I had this in mind for a while but never implemented a standalone binary so far because I always end up writing an integration test anyways.
However, using a standalone version of the pallet based on the revive-runner crate is something people filing in bug reports do anyways, for example:
https://github.com/paritytech/revive/issues/266
https://github.com/paritytech/contract-issues/issues/54
I hope having this maintained in the upstream code base here helps people with desired functionality and also keeping the version up to date. @Subway2023 @sekisamu just hit me up here or open an issue or PR here for any missing features you'd like.
=> revive-runner: add a utility binary for local contract execution

Makefile, crates/runner/Cargo.toml
Make the installation of  `revive-runner` easier:
- Use locked dependencies to avoid issues with downstream crates
- Make the llvm-context crate an optional dependency to the runner
- Add it to the default `test` target ensuring that this actually works
=> revive-runner: install with locked dependencies

crates/integration/codesize.json, crates/llvm-context/src/lib.rs, crates/llvm-context/src/polkavm/const/mod.rs, crates/llvm-context/src/polkavm/context/function/runtime/entry.rs, crates/llvm-context/src/polkavm/context/function/runtime/mod.rs, crates/llvm-context/src/polkavm/context/function/runtime/sbrk.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/runtime-api/src/polkavm_imports.c, crates/runtime-api/src/polkavm_imports.rs, crates/solidity/src/resolc/arguments.rs, crates/solidity/src/yul/parser/statement/object.rs
This PR changes the implementation of the emulated EVM heap memory: Instead of linking in a C implementation the code is emitted directly into the contract module. Which allows making it configurable via a compiler parameter (a follow up PR to this).
=> allow dynamic configuration of the heap memory

CHANGELOG.md, crates/integration/codesize.json, crates/llvm-context/src/lib.rs, crates/llvm-context/src/memory.rs, crates/llvm-context/src/polkavm/context/function/runtime/entry.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/llvm-context/src/polkavm/context/tests.rs, crates/llvm-context/src/polkavm/mod.rs, crates/solidity/src/lib.rs, crates/solidity/src/process/input.rs, crates/solidity/src/process/mod.rs, crates/solidity/src/project/contract/mod.rs, crates/solidity/src/project/mod.rs, crates/solidity/src/resolc/arguments.rs, crates/solidity/src/resolc/main.rs, crates/solidity/src/test_utils.rs
- Allow configuration of the maximum heap and stack size via CLI flags and JSON input settings.
- Increase the default value for the stack size to 32kb.
=> configurable stack and heap memory size

.github/workflows/release-llvm.yml, crates/llvm-builder/src/builtins.rs
The builtins build should use the Ninja generator (MSVC does not build a valid archive).
Tested and verified here: https://github.com/paritytech/revive-alex-workflowtest/releases/tag/untagged-f02d0f574bab8404fead
Closes #305
=> llvm-builder: use the ninja generator for building the builtins on windows

crates/solc-json-interface/src/standard_json/input/mod.rs, crates/solc-json-interface/src/standard_json/input/settings/metadata.rs, crates/solc-json-interface/src/standard_json/input/settings/mod.rs, crates/solc-json-interface/src/standard_json/input/settings/optimizer/details.rs, crates/solc-json-interface/src/standard_json/input/settings/optimizer/mod.rs, crates/solc-json-interface/src/standard_json/input/settings/selection/file/mod.rs, crates/solc-json-interface/src/standard_json/input/settings/selection/mod.rs, crates/solc-json-interface/src/standard_json/input/source.rs
It helps external consumers working with the `revive-solc-json-interface` crate.
=> solc-json-interface: make the input `Clone`able

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/resolc/Cargo.toml, crates/resolc/build.rs, crates/resolc/src/resolc/arguments.rs, crates/resolc/src/resolc/main.rs
- Fetching the commit SHA must not panic if not executed in a git repository.
- Remove the license printer.
=> make resolc crate publishable

Cargo.lock, crates/resolc/Cargo.toml
Do not use wildcard dependency in resolc crate. No sure why the publish dry-run doesn't catch this.
=> do not use wildcard dependency in resolc crate

CHANGELOG.md, crates/resolc/src/tests/cli-tests/src/contracts/yul/memset.yul, crates/resolc/src/tests/cli-tests/src/entities.ts, crates/resolc/src/tests/cli-tests/tests/memset.test.ts, crates/runtime-api/src/polkavm_imports.c
Closes  #350
- Add the missing `memset` builtin which was accidentally deleted in a previous PR.
- Add a compilation test to ensure the `memset` builtin is present.
=> add the missing memset builtin

CHANGELOG.md, crates/llvm-context/src/debug_config/mod.rs, crates/llvm-context/src/polkavm/context/debug_info.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/resolc/src/lib.rs, crates/resolc/src/project/contract/mod.rs, crates/yul/src/parser/statement/expression/function_call/mod.rs, crates/yul/src/parser/statement/if_conditional.rs
This PR fixes and enhances debug info generation:
1. Adds line information for each lowered YUL builtin and the `if` statement.
2. Fixes the debug info source path to match the YUL file of the contract dumped to the `--debug-output-dir`.
This improves inspection of the generated code a lot. Excerpt from `llvm-objdump -Sl /tmp/dbg/contracts_EndpointV2.sol.EndpointV2.so`:
```
; /tmp/dbg/contracts_EndpointV2.sol.EndpointV2.yul:203
;                 let _1 := memoryguard(0x80)
13c3e: 3aa5b023      sd      a0, 0x3a0(a1)
13c42: 38a5bc23      sd      a0, 0x398(a1)
13c46: 38a5b823      sd      a0, 0x390(a1)
13c4a: 08000513      li      a0, 0x80
13c4e: 38a5b423      sd      a0, 0x388(a1)
; /tmp/dbg/contracts_EndpointV2.sol.EndpointV2.yul:204
;                 mstore(64, _1)
13c52: 3885b503      ld …
```
=> emit YUL builtins debug line info and fix debug info source file

CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, crates/explorer/Cargo.toml, crates/explorer/README.md, crates/explorer/src/dwarfdump.rs, crates/explorer/src/dwarfdump_analyzer.rs, crates/explorer/src/lib.rs, crates/explorer/src/location_mapper.rs, crates/explorer/src/main.rs, crates/explorer/src/yul_phaser.rs, crates/yul/src/lexer/token/location.rs, crates/yul/src/parser/statement/expression/function_call/mod.rs, crates/yul/src/parser/statement/function_definition.rs
A maintainable and more precise version of what was a hacky but useful script, exploring the compilers YUL lowering unit.
It analyzes a given shared objects from the debug dump and outputs:
- The count of each YUL statement translated.
- A per YUL statement break-down of bytecode size contributed per.
- Estimated `yul-phaser` cost parameters.
=> the revive-explorer utility

CHANGELOG.md, crates/explorer/src/dwarfdump.rs, crates/explorer/src/dwarfdump_analyzer.rs, crates/explorer/src/location_mapper.rs, crates/explorer/src/main.rs, crates/yul/src/lexer/token/lexeme/literal/mod.rs, crates/yul/src/lib.rs, crates/yul/src/parser/identifier.rs, crates/yul/src/parser/statement/assignment.rs, crates/yul/src/parser/statement/block.rs, crates/yul/src/parser/statement/code.rs, crates/yul/src/parser/statement/expression/function_call/mod.rs, crates/yul/src/parser/statement/expression/function_call/name.rs, crates/yul/src/parser/statement/expression/literal.rs, crates/yul/src/parser/statement/expression/mod.rs, crates/yul/src/parser/statement/for_loop.rs, crates/yul/src/parser/statement/function_definition.rs, crates/yul/src/parser/statement/if_conditional.rs, crates/yul/src/parser/statement/mod.rs, crates/yul/src/parser/statement/object.rs, crates/yul/src/parser/statement/switch/case.rs, crates/yul/src/parser/statement/switch/mod.rs, crates/yul/src/parser/statement/variable_declaration.rs, crates/yul/src/visitor.rs
- Implement the visitor interface. This simplifies working with the AST, for example transformations into other IRs or collecting and analyzing various statistics.
- Switch the explorer to use the visitor interface.
- Add the reciprocal function name conversion for function names.
- Some drive-by cosmetic fixes.
=> YUL tree visitor interface

.github/workflows/test-llvm-builder.yml, .github/workflows/test-wasm.yml, .github/workflows/test.yml
When updating documentation Markdown files, long-running tests still run unnecessarily. With these changes, it will skip running test workflows when PRs only containing changes to such files are opened.
=> Update workflows to skip tests for only `.md` files

crates/integration/codesize.json, crates/llvm-context/src/polkavm/context/function/runtime/deploy_code.rs, crates/llvm-context/src/polkavm/context/function/runtime/entry.rs, crates/llvm-context/src/polkavm/context/function/runtime/runtime_code.rs, crates/llvm-context/src/polkavm/context/mod.rs, crates/llvm-context/src/polkavm/context/runtime.rs, crates/llvm-context/src/polkavm/context/tests.rs, crates/llvm-context/src/polkavm/evm/immutable.rs, crates/yul/src/parser/statement/block.rs, crates/yul/src/parser/statement/expression/function_call/mod.rs, crates/yul/src/parser/statement/function_definition.rs, crates/yul/src/parser/statement/object.rs
Function symbols can clash as we compile multiple YUL `object` definition (different scopes) into the same `LLVM` module (same scope).
- Disambiguate via unique function symbols based its location, i.e. runtime or deploy code.
- Use `LinkOnceODR` linkage for compiler builtin helpers.
=> Prevent frontend function confusion

CHANGELOG.md, crates/solc-json-interface/src/standard_json/input/settings/selection/file/flag.rs, crates/solc-json-interface/src/standard_json/input/settings/selection/file/mod.rs, crates/solc-json-interface/src/standard_json/input/settings/selection/mod.rs, crates/solc-json-interface/src/standard_json/output/contract/mod.rs, crates/solc-json-interface/src/standard_json/output/mod.rs
- do not prune the AST output in standard JSON mode (required for foundry)
- do not serialize the output format if there was not blob produced
=> do not prune the AST output in standard JSON mode

CHANGELOG.md, crates/solc-json-interface/src/standard_json/input/settings/selection/mod.rs, crates/solc-json-interface/src/standard_json/output/mod.rs
Fixes output selection issues for `Foundry` usage. 
- pruning to look at per file settings
- source to include `ast`
`Selection.files` field is reintroduced because that's the way `foundry` functions. it uses per-file output selection
=> Fix output selection issues for `Foundry`
